### ISSUE TITLE
[bug]: STARTTLS still enabled even when turned off.

### ISSUE THREAD

**Issue by KarloDerEchte** [makeplane/plane#3108]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

In 0.14 STARTTLS is still enabled even when it turn it off in the Settings, i cannot switch our Prod instance to 0.14 because of this issue.

`[2023-12-13 06:54:51,782: INFO/MainProcess] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[96f7a400-b8dc-4489-9a2d-7d0092baa480] received
[2023-12-13 06:54:51,902: WARNING/ForkPoolWorker-4] STARTTLS extension not supported by server.
[2023-12-13 06:54:51,906: INFO/ForkPoolWorker-4] Task plane.bgtasks.workspace_invitation_task.workspace_invitation[96f7a400-b8dc-4489-9a2d-7d0092baa480] succeeded in 0.12164234404917806s: None
`

### Steps to reproduce

1. Enter God Mode
2. Turn StartTLS off 
3. Enter a server which does not support starttls
4. see that the bg worker still tries to use it

### Browser

Google Chrome

### Version

Self-hosted

**Comment by NarayanBavisetti** [comment]
@KarloDerEchte Thanks for pointing out the issue, this issue is fixed in the PR #3114

**Comment by KarloDerEchte** [comment]
@NarayanBavisetti  Hi, I see the Merge Request has been pushed into develop, I have a Prod and Dev Instance currently running in my Company for testing and ensuring things like this. I am still not able to send out mails even now when TLS is off on my dev instance, could you check if there is an issue when providing no Username and no Password? We don't need it, we use the SMTP Server as a Relay (Port 25). I am currently not seeing any error in the Console.  We are using the same config in 0.13.2 and its working fine.

**Comment by KarloDerEchte** [comment]
Ok nvmd, i got the email now. But the content is empty.
![image](https://github.com/makeplane/plane/assets/41088744/a7b790f3-37f4-4ddc-bebb-59c6abc45088)


> @NarayanBavisetti Hi, I see the Merge Request has been pushed into develop, I have a Prod and Dev Instance currently running in my Company for testing and ensuring things like this. I am still not able to send out mails even now when TLS is off on my dev instance, could you check if there is an issue when providing no Username and no Password? We don't need it, we use the SMTP Server as a Relay (Port 25). I am currently not seeing any error in the Console. We are using the same config in 0.13.2, and it's working fine there.

**Comment by nic0dk** [comment]
> Ok nvmd, i got the email now. But the content is empty. ![image](https://private-user-images.githubusercontent.com/41088744/290808627-3ca95d4f-b3bb-433d-925d-2dbd4ad79968.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMzkxMzIsIm5iZiI6MTcwNzMzODgzMiwicGF0aCI6Ii80MTA4ODc0NC8yOTA4MDg2MjctM2NhOTVkNGYtYjNiYi00MzNkLTkyNWQtMmRiZDRhZDc5OTY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDIwNDcxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ2Y2RiODNlMGIzYzAwY2FmMTU0OTY3YzRmNmE5NTk5ZGUyZjk5NzBjN2Q4NTEzN2IwYjk4MzM3ZGVmMGI0MjQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.9DFaCqg3obrsqyT70fVsuojS134iCFD7x8QlB21vf3U)
> 

Hi - are you getting these "empty mails" when you invites others ?
