### ISSUE TITLE
[bug]: Custom view on All Issue menu won't open after version v0.15.0

### ISSUE THREAD

**Issue by ihkaru** [makeplane/plane#3516]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When i open All Issue menu on my workspace, loading indicator appear as usual but never finished. The custom view wont open. This happened to all my workspaces on every custom views i made. All premade views is working normally. This happened in workspaces in app.plane.so domain. 
![image](https://github.com/makeplane/plane/assets/60537437/3f715a70-ab68-4b2e-bb37-f91f16b73739)
![image](https://github.com/makeplane/plane/assets/60537437/cec6a5d8-0f17-4878-9333-be5398436c6c)
![image](https://github.com/makeplane/plane/assets/60537437/23bec9db-e7f4-4bbc-bba3-c8a4c0c0dcd4)

![WhatsApp Image 2024-01-31 at 09 12 32_c40b9b35](https://github.com/makeplane/plane/assets/60537437/161a8f13-e2cf-4003-a03b-d4aa84379a3a)
Happened on chrome browser on android tablet too

The views i made is just applying state filters or make it appears as kanban

### Steps to reproduce

1. Open the workspace as usual
2. Open the All Issue menu
3. Open existing custom view that has been made before version v0.15.0

### Browser

Google Chrome

### Version

Cloud

**Comment by srinivaspendem** [comment]
Hi @ihkaru, thank you for bringing attention to this bug. We are actively working on fixing it, and the issue will be resolved soon.

**Comment by rahulramesha** [comment]
This should be fixed in https://github.com/makeplane/plane/pull/3517 , after it is merged and deployed.

**Comment by ihkaru** [comment]
Hi, thank you for your support, really appreciate it.
But how can i get the fixed version on app.plane.so?
The version is still v0.15.0 on the web and the bug is still persist
 
Is there anything i need to do to get the latest version on app.plane.so version?

**Comment by srinivaspendem** [comment]
@ihkaru, we are planning to push the bug fix to our cloud shortly. Once implemented, you will be able to see and experience the fix.

**Comment by ihkaru** [comment]
Thank you very much now its fixed
Really appreciate for what you guys give to the community.
This is very useful tool.
