### ISSUE TITLE
[bug]: unable to send email for ser invites and magic code on docker

### ISSUE THREAD

**Issue by justkelvin** [makeplane/plane#4130]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

While logging in, user can request to login with magic code send via email which was working before and now its not, In the user invite pages, i get a success message of the mail has been sent but it never arrives.

I tested with an SMTP tool to find if the issue was the configuration.

![image](https://github.com/makeplane/plane/assets/76160352/8e449dba-25c8-481d-9616-9a592b5be6f9)

With the same configurations on SMTP Test Tool, i am receiving a test mail

![image](https://github.com/makeplane/plane/assets/76160352/bb41645e-26aa-44b3-8f97-b3acdfa6f8fd)

### Steps to reproduce

1. Go to login, choose login with code, request code severally, check gmail, i am unable to get the mail even in spam folder
2. Go to Organization, go to members and invite user, enter user email, send an invite and it never arrives.
3. Go to /god-mode reconfigure everything again, and try again.
4. Open a test tool, fill in the same options and sent a test email, it works
5. check doc, verify everything again, still not working.

### Environment

Production

### Browser

Google Chrome

### Version

Self-hosted

**Comment by kacperkwapisz** [comment]
i have this issue aswell, for me, it won't even  save the "Turn SSL on" option, it looks like it even is not being sent with the request to the api

**Comment by MichaelErmer** [comment]
same here

**Comment by shervin9** [comment]
I have the same problem

**Comment by NarayanBavisetti** [comment]
A user experienced a similar issue and successfully resolved it by following the steps outlined in this [link](https://discord.com/channels/1031547764020084846/1232336652840472650).
 this might provide a solution for you as well. Let me know if you need further assistance.

**Comment by NarayanBavisetti** [comment]
> i have this issue aswell, for me, it won't even save the "Turn SSL on" option, it looks like it even is not being sent with the request to the api

@kacperkwapisz  the SSL checkbox problem has been resolved in our latest release. Now, the toggled value is being successfully saved.

**Comment by ibtesamlatif2997** [comment]
HI, 

I have installed the docker self hosted version last week and I am still facing issues in sending emails. Same smtp configurations working in other places.

Please help. We can't use it because it sends code to emails for first signup

Thanks,

**Comment by webmasterlv** [comment]
We have the same issue. Self hosted version, test email in god mode works, when inviting member via email does not. It says that email was sent, but it never arrives.

**Comment by pushya22** [comment]
We’re closing this since there have been no new reports related to the issue.
