### ISSUE TITLE
[bug]: Pro user file limit for attachments is 5 Mb, should e 100 Mb

### ISSUE THREAD

**Issue by moigagoo** [makeplane/plane#5355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

I can't attach a file to an issue. The error is Invalid file type or size (max 5 MB).

For context, the file is a short video in .mov.

### Steps to reproduce

1. Buy Pro subscription.
2. Attach a file to an issue.

### Environment

Production

### Browser

None

### Variant

Cloud

### Version

Latest

**Comment by moigagoo** [comment]
Just a quick followup on this issue.

Attaching files still doesn't work but now I'm not seeing any errors at all. Attach button just doesn't do anything.

**Comment by theparthacus** [comment]
that was a temporary error that we fixed.

the storage limit was supposed to be shipped this week, but there's a major security worry that's causing more delay. we need to ensure files are truly private and not just unique-link private. that will take extensive testing.

bear with us for a little more. i have a note to get back to you here myself, so the moment i know better, you will, too.

**Comment by moigagoo** [comment]
@theparthacus any news about this fix? This is a very annoying bug.

**Comment by theparthacus** [comment]
this is fixed. apologies for the delay. should you be interested, this change was blocked by our move to private S3 buckets, which happened last weekend. your uploads, even heavier ones now, are more secure.

**Comment by moigagoo** [comment]
@theparthacus Unfortunately, I'm still unable to attach files over 5 Mb.

**Comment by moigagoo** [comment]
@theparthacus I have just checked it, and the issue is still there.

**Comment by pankajmyt** [comment]
I have set value to 512mb on nginx. Still getting this error. Any other setting that I need to update?
