### ISSUE TITLE
[bug]: Changing background in project settings doesn't work properly

### ISSUE THREAD

**Issue by KCynk** [makeplane/plane#5817]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

Your project -> Settings 
Settings (General Section)
Change Cover -> Upload
Drag and drop .png -> Upload and Save
Update project
Results
![image](https://github.com/user-attachments/assets/22f67570-660b-441a-8058-cccd1be7be22)

### Steps to reproduce

Your project -> Settings 
Settings (General Section)
Change Cover -> Upload
Drag and drop .png -> Upload and Save
Update project
Results
![image](https://github.com/user-attachments/assets/22f67570-660b-441a-8058-cccd1be7be22)

### Environment

Production

### Browser

Mozilla Firefox

### Variant

Self-hosted

### Version

v0.23.1

**Comment by KCynk** [comment]
also i cant even add picture to Pages
![image](https://github.com/user-attachments/assets/b72e1477-044b-495b-8681-774c78ce8c5e)

**Comment by talibraath** [comment]
please assign me

**Comment by pushya22** [comment]
@KCynk this is resolved and will be part of our upcoming release

**Comment by pushya22** [comment]
We are unable to reproduce the second issue on our end. Uploading images to pages is functioning correctly in the latest release, v0.23.1. Could you provide detailed steps to reproduce the issue so we can investigate further?

**Comment by plsoftware** [comment]
Still experiencing this bug on v1.2.3 (self-hosted, Docker via Portainer).

The cover image change does not persist when updating an existing project via Settings. Interestingly, cover images set at project creation time save correctly — the bug is specific to the update flow.

After further testing, the bug appears to be specific to selecting an image from the **Unsplash picker** — the selected image does not persist on save. However, **uploading your own image** via the Upload tab in the same modal works correctly and saves as expected.

**Additional findings:**
- If the Unsplash API key returns a 401 (e.g. invalid or not yet configured in God Mode), the cover picker modal triggers a continuous redirect loop between the settings page and the login page, making the settings page completely unusable until the key is fixed
- Once a valid Unsplash key is set in God Mode, the redirect loop stops and the modal opens correctly — but images selected **from the Unsplash picker** still do not persist on save
- Inspecting the API logs confirms the PATCH request when saving project settings does not include the `cover_image` field when an Unsplash image is selected, indicating the Unsplash selection is not being passed through to the form state

Hope this helps narrow down the fix.
