### ISSUE TITLE
[bug]: Page content not available

### ISSUE THREAD

**Issue by imoiseev** [makeplane/plane#6206]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

If I create a page, another person sees the page in the list, sees its title, but does not see the content.

The content that I add is not visible to him. Moreover, he can add content, it is saved, but I also do not see his content.

### Steps to reproduce

Create a page in any project from any account. Fill it with content.

Try opening this page from another account.

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v0.24.1

**Comment by akshat5302** [comment]
Hey @imoiseev, please verify if the live service is working by checking its health endpoint at: `http://<domain-name>/live/health`?
Also, please confirm that the WebSocket connection is established correctly. Please open the website, inspect it using developer tools, navigate to the **Network** tab, select **WS**, and verify the WebSocket connection.

**Comment by imoiseev** [comment]
http://<domain-name>/live/health
`{"status":"OK"}`

![Снимок экрана 2024-12-16 в 18 54 44](https://github.com/user-attachments/assets/9f98b1e2-838c-4ddc-8fa4-f797a1ba3241)
![Снимок экрана 2024-12-16 в 18 55 04](https://github.com/user-attachments/assets/c12ae1dc-8104-4774-a7e9-e558bc02cf80)
![Снимок экрана 2024-12-16 в 18 55 10](https://github.com/user-attachments/assets/bc4a1f58-4af1-44f3-a293-21c1810c9c31)

**Comment by akshat5302** [comment]
Do you have any other external proxy enabled apart from `plane-proxy`?

**Comment by smonksi** [comment]
I am self-hosting v0.24.0 and experiencing a similar issue. 

### Current behavior
If I create a page with content, I cannot see that content on any browser, other than the one where I created the content. This applies to browsers on the same machine and on browsers of alternate machines. 

As with the OP, I can add conent on other browsers to the page, but it is not visible in the original browser that created the page.

This all relates to a single account.

### Steps to reproduce
Create a page in any project from any account. Fill it with content.

Try opening this page with the same account on another browser.

### Set Up
Note that I am using a proxy server to direct external domain traffic to the local IP address of the VM containing the plane instance.

**Comment by akshat5302** [comment]
Hi @smonksi and @imoiseev,  

Could you confirm that your external proxy configuration matches the [template](https://developers.plane.so/self-hosting/govern/reverse-proxy#configuration-templates)

For example, if you are using NGINX, adding the following headers should resolve the WebSocket issue:  

```  
proxy_http_version 1.1;  
proxy_set_header Upgrade $http_upgrade;  
proxy_set_header Connection "upgrade";  
```

**Comment by smonksi** [comment]
Hi @akshat5302 

Updated NGINX as per your settigns and it all appears to be working perfectly now. Thank you!

**Comment by akshat5302** [comment]
This issue is resolved, closing it now.

**Comment by imoiseev** [comment]
It didn't help me.

**Comment by vladimirevstratov** [comment]
Also has reverse proxy on nginx, using template for it from docs (link was mentioned previously), but websocket still failed.

**Comment by akshat5302** [comment]
Hey @vladimirevstratov, do you have an external reverse proxy configured to point to plane-proxy?

**Comment by vladimirevstratov** [comment]
> Hey [@vladimirevstratov](https://github.com/vladimirevstratov), do you have any external reverse proxy configured to point to the plane-proxy container?

Yeah, i do. And i use nginx proxy config from template

**Comment by akshat5302** [comment]
Could you please share the external proxy configuration you set up for Plane?

**Comment by vladimirevstratov** [comment]
> Could you please share the external proxy configuration you set up for Plane?

https://developers.plane.so/self-hosting/govern/reverse-proxy#nginx

Used this templane

`
server {
server_name <domain>;

location / {
    proxy_pass http://<plane-host-ip>:<plane-host-port>/;
    
    # Set headers for proxied request
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host  $host;
    proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
    proxy_set_header X-Real-IP         $remote_addr;
    
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_http_version 1.1;
}

client_max_body_size 10M;

listen 443 ssl; # managed by Certbot
ssl_certificate /etc/letsencrypt/live/<domain>/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/<domain>/privkey.pem;
include /etc/letsencrypt/options-ssl-nginx.conf;
#ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;
}

server {
if ($host = <domain>) {
    return 301 https://$host$request_uri;
}

listen 80;
server_name <domain>;
return 404;
}
`

**Comment by akshat5302** [comment]
This looks good. Could you share the network tab logs for the WebSocket connection?
Something like this - 

<img width="1769" alt="Image" src="https://github.com/user-attachments/assets/dedda646-c222-41fe-b8b7-e507b326e669" />

**Comment by vladimirevstratov** [comment]
> This looks good. Could you share the network tab logs for the WebSocket connection? Something like this -
> 
> <img alt="Image" width="1769" src="https://private-user-images.githubusercontent.com/55329820/408029961-dedda646-c222-41fe-b8b7-e507b326e669.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzgyMjUwMzgsIm5iZiI6MTczODIyNDczOCwicGF0aCI6Ii81NTMyOTgyMC80MDgwMjk5NjEtZGVkZGE2NDYtYzIyMi00MWZlLWI4YjctZTUwN2IzMjZlNjY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTMwVDA4MTIxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBjYzQ4YTY4ZWU3ZTcwNzE4ZWRjZGRjNzg0N2I2NmNkNGUyNzg4Yjc4NzAzMmUxMjcyMDE0MzhjYTdmZDNkYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.zTPPja7BEJzclfORYbpeozks41GZvW_dqduNwk8WEXw">
> Check if the websocket connection is done properly or not

<img width="989" alt="Image" src="https://github.com/user-attachments/assets/319cea8b-a033-4e28-90e3-c5364ee9783c" />

**Comment by akshat5302** [comment]
The network tab shows the status as "Finished" instead of 101, which suggests a possible misconfiguration in your Nginx setup. Please review and fix it.

For reference, check the [Troubleshooting guide](https://docs.plane.so/core-concepts/pages/overview#troubleshooting).

**Comment by vladimirevstratov** [comment]
> The network tab shows the status as "Finished" instead of 101, which suggests a possible misconfiguration in your Nginx setup. Please review and fix it.
> 
> For reference, check the [Troubleshooting guide](https://docs.plane.so/core-concepts/pages/overview#troubleshooting).

thank you, but it didn't help

**Comment by vladimirevstratov** [comment]
Ok, i removed reverse proxy nginx, trying now to start only plane on https. 
It doesn't work.

plane.appinbox.net

**Comment by vladimirevstratov** [comment]
Ok, fixed it.
- Reloaded Nginx properly after applying changes
- Removed `ro` flag from nginx conf for properly applying it with nginx
