### ISSUE TITLE
[bug]: Provided default application user name and password don't work

### ISSUE THREAD

**Issue by andy47** [makeplane/plane#719]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I have the application running via docker on my laptop I can't log into the application using the default user name and password provided on https://docs.plane.so/self-hosting

The login fails and I see this pop-up error message;

![image](https://user-images.githubusercontent.com/782758/230128524-1c0749b2-bf24-41b4-bc96-f91ef3b0a918.png)

### Steps to reproduce

1. Start the application using `docker-compose up`
2. Go to the application sign in page (on my machine that is http://localhost:8005/signin )
3. Attempt to login with the default user name and password supplied on https://docs.plane.so/self-hosting
4. Login fails.

### Environment

Deploy preview

### Version

Self-hosted

**Comment by airdogvan** [comment]
same here

**Comment by sphynxux** [comment]
Thanks for reporting this @andy47, @airdogvan. We are working on fix for this with high priority. We'll revert back soon.

**Comment by galaris** [comment]
same

**Comment by pablohashescobar** [comment]
We have fixed the above issue in our `develop` branch we are still aggressively testing it and fixing any bugs.

**Comment by vihar** [comment]
Related to #477.

**Comment by soxrok2212** [comment]
Still seeing this bug on develop branch

**Comment by tkerr97** [comment]
Same issue here, clicking on forgot password shows "Setting up you workspace" forever

**Comment by pablohashescobar** [comment]
Greetings everyone, I am the maintainer of Plane. I would like to inform you that the error you have encountered has been resolved in our latest development branch. In order to successfully apply this fix, kindly delete all volumes, network, and the container itself. After which, please proceed with rebuilding the images. Thank you.

**Comment by andy47** [comment]
Same problem here at @tkerr97 reports. 

I already have services running on port 80 and 3000 on the host machine. So I changed nginx to run on port 8005 and plane-web to run on port 3003.

Same error message.

**Comment by pablohashescobar** [comment]
Hey, can you also please try by updating the Dockerfiles for both backend and frontend `Dockerfile.api` and `Dockerfile.web` also the compose as well.

**Comment by tkerr97** [comment]
On a clean machine I did the following:
1. Cloned the repo
2. Ran setup.sh with my IP
3. Edited the docker-compose.yml to have the port I want
4. Ran `docker-compose up`
5. Attempted to login with the default username and password and still got the error

**Comment by galaris** [comment]
Develop branch solved for me, but I needed to run this:
`docker compose up --build`

Thanks to n1kh1l!

**Comment by ada-Alex** [comment]
Still getting this error when changing the nginx port in docker-compose.yml to - 4000:80 as I can't use port 80 on my machine.

**Comment by heromiyo** [comment]
am still getting this error after doing all the suggested options, this is what i see in the logs nginx          | 172.18.0.1 - - [19/Apr/2023:09:34:22 +0000] "POST /api/sign-in/ HTTP/1.1" 502 559 "http://localhost/signin" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/111.0.0.0 Safari/537.36"
nginx          | 2023/04/19 09:34:22 [error] 23#23: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: , request: "POST /api/sign-in/ HTTP/1.1", upstream: "http://172.18.0.2:8000/api/sign-in/", host: "localhost", referrer: "http://localhost/signin"

**Comment by heromiyo** [comment]
for error above it was locally on windows but i have deployed the same app on the cloud VM and the branch is develop for both and for the cloud VM one i just cloned the repo just now and did the README step by step
 https://80-port-c649136594064ade.labs.kodekloud.com/signin

**Comment by heromiyo** [comment]
please use https://80-port-c649136594064ade.labs.kodekloud.com/signin to test login using default credentials

**Comment by pablohashescobar** [comment]
Hey @heromiyo can you check if the backend container is running

**Comment by heromiyo** [comment]
it is, here is a terminal you can use to check aswel @pablohashescobar  
https://terminal-c649136594064ade.labs.kodekloud.com/

**Comment by heromiyo** [comment]
@pablohashescobar still there but the api url is updated https://80-port-c649136594064ade.labs.kodekloud.com/signin

**Comment by heromiyo** [comment]
and also fails on localhost 
![image](https://user-images.githubusercontent.com/39757927/233058952-9f29a54a-859e-45a1-9e85-33f7da471b15.png)

**Comment by pablohashescobar** [comment]
Hi @heromiyo it would be awesome if you could send your envs at `apiserver/.env` and `apps/app/.env` and also the nginx configuration.

**Comment by pablohashescobar** [comment]
Hello everyone,

We have updated our docker setup and now have pushed pre-built images to DockerHub as well which can be used by using `docker-compose -f docker-compose-hub.yml up`. Detailed docs can be found here https://docs.plane.so/self-hosting

**Comment by HearthCore** [comment]
Wonder if a comment will reopen this.

I've cloned the lasted -dev branch, clean setup, still incorrect password for default admin user.

**Comment by pablohashescobar** [comment]
Hey @HearthCore it would be awesome if you could share browser network logs and  docker logs as well.

**Comment by Alcatraz077** [comment]
I've ran into this as well. Brand new Ubuntu 22.04 box. I'll gladly provide docker logs, but which containers? All of them?

As for network logs, when I attempt to login with the default creds, it sends the following headers:
```
OPTIONS /api/sign-in/ undefined
Host: localhost
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/113.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Access-Control-Request-Method: POST
Access-Control-Request-Headers: content-type
Referer: http://plane:3000/
Origin: http://plane:3000
DNT: 1
Connection: keep-alive
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: cross-site
```

With the response of:
```
Response body is not available to scripts (Reason: CORS Failed)
```

**Comment by shadowjig** [comment]
When will this fix be deployed to the docker images on hub.docker.com

**Comment by pablohashescobar** [comment]
Hi @shadowjig, this is already fixed. You may have to run `./setup.sh localhost` since the new changes are not deployed to docker hub yet we are still testing some changes.

**Comment by MostHated** [comment]
I just tried this as well, having the same issue. Unable to login with default creds

**Comment by chengdujin** [comment]
Team, come on! If new comers can't even sign in to the system, confidence will wear off soon!

This is quite a critical bug. Get it done.

**Comment by pablohashescobar** [comment]
The issue has been successfully resolved. If you're still encountering problems with port 80, you can manually adjust the host port in the nginx container and rerun the setup. In the upcoming version, we will also introduce the ability to update the nginx port through environment variables, which will provide more flexibility. Don't forget to provide the correct URL to ./setup.sh as well.

These steps should help address any lingering issues you may be facing. We appreciate your understanding and cooperation. If you have any further questions or need assistance, feel free to reach out to me directly or join our Discord server. Our team will be more than happy to assist you.

**Comment by MostHated** [comment]
Interesting. I attempted to use a port other than 80 right out of the gate. For all my local services I never use 80, and use an internally hosted domain (which I passed to the setup.sh) pointing to a Caddy v2 server which in turn reverse proxies to the port I have assigned in whatever service. That said, I attempted to use 8089 as the port from the first go, and have this issue still.

**Comment by gomarcd** [comment]
I'm still having the issue as well.

To start clean, I did:

```
docker compose down -v
docker prune system --all
cd .. && sudo rm -r plane
git clone -b master https://github.com/makeplane/plane.git && cd plane
./setup.sh http://plane.domain.tld
nano .env
set -a; source .env; set +a;
docker-compose -f docker-compose-hub.yml up
```

I edited .env to change nginx port number accordingly and did `docker-compose -f docker-compose-hub.yml up`

This still produced the same error message. What am I missing?

**Comment by MostHated** [comment]
Yeah, I see that it is 'resolved'. Unfortunately, I, and several others, are still having the same issue. I wiped out all container images, stored volumes on the system, etc, etc, a clean slate, tried again just to be sure. I tried both with a default of 80 (just to see), a different port, I also tried changing what was listed in `DEFAULT_USERNAME` and `DEFAULT_PASSWORD` fields before firing it up, to see if that would make a difference. I tried both with just the standard docker-compose.yml, and the docker-compose-hub.yml. I tried everything I could think of to try but always had the same end result  of:

![](https://img.instance.id/pfQ4XgzN9Vf4/direct)

**Comment by pablohashescobar** [comment]
Hi @MostHated, sorry for the inconvenience caused it would be awesome if you could share the browser network logs and also container logs for both frontend and backend.

**Comment by srvadmindianoil** [comment]
Hi,
Am facing the same issue. Unable to log in using the default credentials.
![plane-login-error](https://github.com/makeplane/plane/assets/136163208/03d926e0-f380-41ea-8647-c655c4c3f08e)

**Comment by pablohashescobar** [comment]
Hi @srvadmindianoil, it would be awesome if you could share browser network logs and logs for both frontend and backend containers.

**Comment by Joshua2504** [comment]
Any idea when this will be fixed in stable branch?

**Comment by pablohashescobar** [comment]
Hi @shadowjig, you are correct it's possible that this issue is caused by Nginx. To confirm, could you please try visiting the `/api/users/me/` endpoint in your browser and let me know the response you receive? Additionally, I would like to inquire if you are solely using the Plane setup or if there are any other proxies in front of the Plane setup as well.

**Comment by shadowjig** [comment]
@pablohashescobar I tried to hit that endpoint and it gave me an ERR_TOO_MANY_REDIRECTS and then reloaded and gave me another error (I think it was 401 unauthorized).  So I reloaded the based URL with that endpoint and I was at the onboarding page.

**Comment by pablohashescobar** [comment]
Got it @shadowjig, thanks for the update.

**Comment by mariushosting** [comment]
I think 90% of users facing the same issue. Clean install same issue. Can't login with the default credentials.

**Comment by ForsakenRei** [comment]
Glad I'm not the only one, neither the default credential nor what I put into `.env` works.

**Comment by pablohashescobar** [comment]
Hi folks, this bug has been resolved it would be awesome if you could share your browser network logs and logs for both frontend and backend container or feel free to hop on to our discord server and we would be happy to help you over there.

**Comment by mariushosting** [comment]
> Hi folks, this bug has been resolved it would be awesome if you could share your browser network logs and logs for both frontend and backend container or feel free to hop on to our discord server and we would be happy to help you over there.

I don't think this bug it's fully solved since I can replicate this issue on all fresh installation. I will come on discord.

**Comment by shadowjig** [comment]
@mariushosting @ForsakenRei the problem is that the fix has not been deployed to the latest docker containers yet.  0.71-dev was released before this issue was fixed.  In order to try out the fix, you need to clone the repo and then build the containers locally by running the docker-compose.yml (not the hub one).  Also follow the other commands in the self hosted documentation.

Or just wait for the next release of the docker containers.

I will say I still had an issue even after I built them locally.  There's still an issue in their app or proxy config that causes one of the endpoints to be unavailable.

**Comment by pablohashescobar** [comment]
Closing this issue as it has been fixed.

**Comment by codenoid** [comment]
sorry, this still not working

```
# Default Creds
DEFAULT_EMAIL="xxxx@gmail.com"
DEFAULT_PASSWORD="mypassword"
```

then I'm making sure again by doing 

```
docker compose -f docker-compose-hub.yml down --rmi all -v
```

then deploy it again

still no works

**Comment by daxdax89** [comment]
Still not resolved.

**Comment by ketansp** [comment]
Still not resolved
