### ISSUE TITLE
[bug]: Work Item Opened from Home Page Recents Missing Cycle and Module

### ISSUE THREAD

**Issue by leedsjb** [makeplane/plane#7550]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Current behavior

When I open a Work Item from the Plane Home Page recents section the Work Item is missing its assigned Cycle and Module. I have confirmed when clicking "Expand" to open the Work Item in full screen the Cycle and Module appear properly. 

I expect all Work Items to display consistent information regardless of the view.

### Steps to reproduce

1. Navigate to Plane Home Page
2. Open a Work Item from the Recents list
3. Observe missing information

Current State:
<img width="354" height="81" alt="Image" src="https://github.com/user-attachments/assets/8a5b8f68-8edf-4be2-b051-6bc2fb0676a4" />

Expected State:
<img width="300" height="88" alt="Image" src="https://github.com/user-attachments/assets/ffb4750e-b971-460c-9710-8926bf61f00f" />

### Environment

Production

### Browser

Google Chrome

### Variant

Self-hosted

### Version

v1.13.0

**Comment by yevin215** [comment]
I believe this issue is already fixed

**Comment by elenamontes-oss** [comment]
I am still seeing this issue as well: 
<img width="277" height="95" alt="Image" src="https://github.com/user-attachments/assets/15ab7ca0-7167-42fb-b54c-b2debf63b6ae" />

To add some more context, I am also unable to select existing modules or cycles from those dropdowns. 

**Environment**
Production

**Browser**
Google Chrome

**Variant**
Self-hosted

**Version**
v2.5.0
