### ISSUE TITLE
[bug]: Pasting image in 'page' causes a HTTP 400 error

### ISSUE THREAD

**Issue by Enriquito** [makeplane/plane#757]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behavior

When I paste a image in a page block. I see a spinner going but nothing is getting uploaded. When I check the network tab there is a 400 error that de 'workspace id' is missing: `{ error: "Workspace id is required" }` I tested this on your cloud bases app.

The image should be added to the page block.

### Steps to reproduce

1. Create a page
2. Add a block or reuse an exciting one.
3. Copy a image in your clipboard
4. Paste it in a block.
5. See the error in the network tab.

### Environment

Production

### Version

Cloud

**Comment by vihar** [comment]
Hey @Enriquito, thanks for reporting this bug. Pages on Plane is a new feature, and we are still aggressively testing it. We'll try to fix this on our next release.

**Comment by rhea0110** [comment]
Hey @Enriquito, may I know which browser you are using?

**Comment by Enriquito** [comment]
Hi @rhea0110 I use Firefox 111.0.1 (64-bit) macOS.

**Comment by rhea0110** [comment]
Hey @Enriquito, we are pleased to inform you that this issue has been resolved in our latest release, v0.5, and is now available for use in the app.plane.so.

**Comment by Enriquito** [comment]
Hi @rhea0110,

Just tried it. But sadly still the same error.

**Comment by rhea0110** [comment]
Hey @Enriquito, we are pleased to inform you that this issue has been resolved in our latest release and is now available for use in the app.plane.so.
